CREATE TABLE XX_ERROR_LOG(ERROR_ID NUMBER, INTEGRATION_NAME VARCHAR2(100), FLOW_INSTANCE_ID NUMBER, FAULT_MESSAGE VARCHAR2(500), FAULT_TYPE VARCHAR2(100), FAULT_DATETIME DATE )
/
CREATE SEQUENCE XX_ERROR_LOG_ID_S start with 50 increment by 1;
/